name: color_scheme_grid
description: "A Flutter widget that displays a grid of Material color scheme colors."
version: 1.0.0
homepage: https://github.com/devloop1000/color_scheme_grid

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^2.0.1
  # Flutter test tools
  flutter_test:
    sdk: flutter
  # Test lib.
  test: